server:
  port: 8085
  servlet:
    context-path: /api
  error:
    include-stacktrace: always

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:vehicle-db
    #    url: jdbc:postgresql://localhost:5433/machines-db
    username: sa
    password: sa

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
  liquibase:
    contexts: development
